version: '3.7'
services:
  frontvue:
    build:
      context: ./vue
      dockerfile: Dockerfile-vue
    ports:
      - 8080:8080
    volumes:
      - ./vue/clockstudy:/vue/clockstudy
      # - /erules/node_modules
    container_name: clockstudy-vue-dev
    tty: true
